---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
- type: directory
  path: docs/presentation
  label: Presentation
  create: all
  match: "**/*"
- type: directory
  path: docs/counter
  label: Counter
  create: all
  match: "**/*"
- type: directory
  path: docs/guide
  label: Guide
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: false
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
  publish_command: yarn build
  output_directory: ".vuepress/dist"
  preview_command: public
